### ISSUE TITLE
Version 2.0 Milestone

### ISSUE THREAD

**Issue by bgulanowski** [Shopify/mobile-buy-sdk-android#45]
# Shopify Android Buy SDK 2.0

## Overview

Shopify's APIs are evolving, and the Buy SDK is being revised to keep in sync. The next version of the SDK is underway, with a targeted release date for the end of April, 2016. Many of the features of the next version area already in use in private projects within Shopify. Over the next few weeks, we'll be cleaning up and deploying those features into this repository.

New 2.0 changes will be integrated on the version-2 integration branch. When it's ready, it will take over as the master branch. The current develop branch will be renamed and deprecated at that time.

## Goals for Buy SDK 2.0

- support for the latest version of the Shopify Checkout API
- support for the latest version of the Shopify Channels API
- support for the new Shopify Customer API
- streamlined framework, focussed solely on exposing API features
- sample UI provided as part of sample apps
- support for Android Pay

## Milestone Issues

- [x] Relocate UI code
- [x] Update checkout API: https://github.com/Shopify/mobile-buy-sdk-android/issues/44
- [x] Update to App Extensions API: https://github.com/Shopify/mobile-buy-sdk-android/issues/43
- [x] Add customer models: https://github.com/Shopify/mobile-buy-sdk-android/issues/41
- [x] Add customer API interfaces: https://github.com/Shopify/mobile-buy-sdk-android/issues/42
- [x] Update to Retrofit 2.0: https://github.com/Shopify/mobile-buy-sdk-android/issues/46
- [x] Update to OkHttp 3.0: https://github.com/Shopify/mobile-buy-sdk-android/issues/49
- [x] Support Android Pay

**Comment by bgulanowski** [comment]
@krisorr @yervantk @davidmuzi

**Comment by bgulanowski** [comment]
@krisorr please feel free to add more specific issues and link them from here.

**Comment by fananta** [comment]
#44 is closed so updating that in the checklist above.

**Comment by krisorr** [comment]
I am going to close this ticket, any open issues have their own tickets.

**Comment by reggi** [comment]
When is this going to be released? My team is looking for a way to do customer login.

**Comment by proselyte6** [comment]
Hello, when will the 2.0 SDK be released? I want to implement customer login/sign up activity in a mobile app
